name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 0 * * *" # 毎日UTC 0:00に自動更新
  workflow_dispatch: # 手動での実行ボタンを有効化

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_CARDS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
